export 'CalendarView.dart';
//export 'ConversationIndexedItemView.cs
//export 'FindConversationResults.cs
export 'FindFoldersResults.dart';
export 'FindItemsResults.dart';
//export 'FindPeopleResults.cs
export 'FolderView.dart';
//export 'GetUserPhotoResults.cs
export 'GroupedFindItemsResults.dart';
export 'Grouping.dart';
export 'ItemGroup.dart';
export 'ItemView.dart';
export 'OrderByCollection.dart';
export 'PagedView.dart';
//export 'PeopleIndexedItemView.cs
//export 'PeopleQueryMode.cs
//export 'PeopleQueryResults.cs
export 'SeekToConditionItemView.dart';
export 'ViewBase.dart';